### ISSUE TITLE
Mining

### ISSUE THREAD

**Issue by Dennan** [Dennan/DataMining#3]
We need to mine the trends from reddit. How many comments from X date to Y date were positive for a given candidiate? Which one "won" in popularity? Did things change after key events?

**Comment by nmulligan** [comment]
Here's a list of key dates that might be worth considering checking comments around.

Trump announces presidential candidacy:
June 16, 2015

Trump named Republican Candidate:
May 3, 2016

Clinton named Democratic Candidate:
July 26, 2016

Clinton’s “Deplorables" comment:
September 9, 2016

Video of Trump making sexist comments released:
October 7, 2016

Debates:
September 26, 2016
October 9, 2016
October 19, 2016

Election Day:
November 8, 2016

**Comment by Dennan** [comment]
Two more dates: 

October 28, 2016: FBI reopens Clinton investigation
November 7, 2016: FBI announces investigation is finished, no charges against Clinton

**Comment by IrinaAugust** [comment]
We can also look for one week after election (8th - 15th)
