### ISSUE TITLE
Paper: intro and why sentiment analysis matters

### ISSUE THREAD

**Issue by IrinaAugust** [Dennan/DataMining#5]
First portion of the paper. This could be followed by "Ralated Work" section

**Comment by Nolan-Labelle** [comment]
Should this be broken down into two separate ones? "Intro" and "Why sentiment analysis matters"?

**Comment by IrinaAugust** [comment]
Paper with the intro https://drive.google.com/open?id=0B84BFZihURanT3VxRk5MdlIwTzg
